# fly.toml app configuration file generated for mi-ollama-server on 2025-03-05T12:34:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mi-ollama-server'
primary_region = 'mad'

[build]
  image = "ollama/ollama"

[[services]]
  internal_port = 11434
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80

